-- Ejecuta este archivo una sola vez en el SQL Editor de tu proyecto Supabase.

create table if not exists public.movimientos_mathcoins (
  id bigint generated by default as identity primary key,
  alumno_id bigint not null references public.alumnos(id) on delete cascade,
  cantidad integer not null check (cantidad <> 0),
  causa text,
  saldo_anterior integer not null,
  saldo_resultante integer not null check (saldo_resultante >= 0),
  profesor_id uuid not null default auth.uid(),
  created_at timestamptz not null default now()
);

create index if not exists movimientos_mathcoins_alumno_fecha_idx
  on public.movimientos_mathcoins (alumno_id, created_at desc);

alter table public.movimientos_mathcoins enable row level security;

drop policy if exists "maestro lee movimientos" on public.movimientos_mathcoins;
create policy "maestro lee movimientos" on public.movimientos_mathcoins
  for select to authenticated using (true);

drop policy if exists "alumno consulta movimientos" on public.movimientos_mathcoins;
create policy "alumno consulta movimientos" on public.movimientos_mathcoins
  for select to anon using (true);

create or replace function public.registrar_movimiento_mathcoins(
  p_alumno_id bigint,
  p_cantidad integer,
  p_causa text default null
) returns public.alumnos
language plpgsql
security definer
set search_path = public
as $$
declare
  v_anterior integer;
  v_nuevo integer;
  v_alumno public.alumnos;
begin
  if auth.uid() is null then raise exception 'Debes iniciar sesión como maestro'; end if;
  if p_cantidad = 0 then raise exception 'La cantidad no puede ser cero'; end if;

  select saldo into v_anterior from public.alumnos where id = p_alumno_id for update;
  if not found then raise exception 'Alumno no encontrado'; end if;

  v_nuevo := greatest(0, coalesce(v_anterior, 0) + p_cantidad);
  update public.alumnos
    set saldo = v_nuevo, nivel = floor(v_nuevo / 500.0)::integer + 1
    where id = p_alumno_id returning * into v_alumno;

  insert into public.movimientos_mathcoins
    (alumno_id, cantidad, causa, saldo_anterior, saldo_resultante, profesor_id)
  values
    (p_alumno_id, v_nuevo - coalesce(v_anterior, 0), nullif(trim(p_causa), ''), coalesce(v_anterior, 0), v_nuevo, auth.uid());

  return v_alumno;
end;
$$;

revoke all on function public.registrar_movimiento_mathcoins(bigint, integer, text) from public;
grant execute on function public.registrar_movimiento_mathcoins(bigint, integer, text) to authenticated;

-- Lectura necesaria para localizar alumnos y mostrar rankings.
alter table public.alumnos enable row level security;
drop policy if exists "mathwallet consulta alumnos" on public.alumnos;
create policy "mathwallet consulta alumnos" on public.alumnos
  for select to anon, authenticated using (true);
